services:
  postgres:
    image: postgres:15-alpine
    container_name: mf_tracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mf_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mf_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - mf_network

  api:
    build:
      context: ./Server
      target: api
    restart: always
    ports:
      - "9001:9001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mf_network

  sync:
    build:
      context: ./Server
      target: sync
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BACKFILL_LIMIT: ${BACKFILL_LIMIT:-50}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mf_network

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./Client/build/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - mf_network

volumes:
  pg_data:

networks:
  mf_network:
    driver: bridge
